# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mimoy\Documents\GitHub\mts-pos\app\ui\widget\Loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogLoading(object):
    def setupUi(self, DialogLoading):
        DialogLoading.setObjectName("DialogLoading")
        DialogLoading.resize(314, 71)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogLoading)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(DialogLoading)
        self.label.setEnabled(True)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)

        self.retranslateUi(DialogLoading)
        QtCore.QMetaObject.connectSlotsByName(DialogLoading)

    def retranslateUi(self, DialogLoading):
        _translate = QtCore.QCoreApplication.translate
        DialogLoading.setWindowTitle(_translate("DialogLoading", "Dialog"))
        self.label.setText(_translate("DialogLoading", "Please wait..."))
