# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mimoy\Documents\GitHub\mts-pos\app\ui\dialogs\edit_current_userui.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEditCurrentUser(object):
    def setupUi(self, DialogEditCurrentUser):
        DialogEditCurrentUser.setObjectName("DialogEditCurrentUser")
        DialogEditCurrentUser.resize(486, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogEditCurrentUser)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(DialogEditCurrentUser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.scrollArea = QtWidgets.QScrollArea(DialogEditCurrentUser)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 466, 230))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditFullName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditFullName.setObjectName("lineEditFullName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditFullName)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.lineEditBirthDate = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditBirthDate.setObjectName("lineEditBirthDate")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditBirthDate)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditBirthDate_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditBirthDate_2.setObjectName("lineEditBirthDate_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditBirthDate_2)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditPassword = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditPassword.setObjectName("lineEditPassword")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditPassword)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditMobileNumber = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditMobileNumber.setObjectName("lineEditMobileNumber")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEditMobileNumber)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(DialogEditCurrentUser)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonCreate = QtWidgets.QPushButton(DialogEditCurrentUser)
        self.pushButtonCreate.setObjectName("pushButtonCreate")
        self.horizontalLayout.addWidget(self.pushButtonCreate)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogEditCurrentUser)
        QtCore.QMetaObject.connectSlotsByName(DialogEditCurrentUser)

    def retranslateUi(self, DialogEditCurrentUser):
        _translate = QtCore.QCoreApplication.translate
        DialogEditCurrentUser.setWindowTitle(_translate("DialogEditCurrentUser", "Edit"))
        self.label_6.setText(_translate("DialogEditCurrentUser", "MTS POS"))
        self.label_4.setText(_translate("DialogEditCurrentUser", "Full name"))
        self.label_5.setText(_translate("DialogEditCurrentUser", "Birthdate"))
        self.label.setText(_translate("DialogEditCurrentUser", "Username"))
        self.label_2.setText(_translate("DialogEditCurrentUser", "Password"))
        self.label_3.setText(_translate("DialogEditCurrentUser", "Mobile number"))
        self.pushButtonCancel.setText(_translate("DialogEditCurrentUser", "Cancel"))
        self.pushButtonCreate.setText(_translate("DialogEditCurrentUser", "Save"))
