# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mimoy\Documents\GitHub\mts-pos\app\views\templates\EditItemSold.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEditItemSold(object):
    def setupUi(self, DialogEditItemSold):
        DialogEditItemSold.setObjectName("DialogEditItemSold")
        DialogEditItemSold.resize(699, 506)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogEditItemSold)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_6 = QtWidgets.QLabel(DialogEditItemSold)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.scrollArea = QtWidgets.QScrollArea(DialogEditItemSold)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 679, 436))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditItemName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditItemName.setEnabled(False)
        self.lineEditItemName.setObjectName("lineEditItemName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditItemName)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditOnHand = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditOnHand.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditOnHand.setObjectName("lineEditOnHand")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditOnHand)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditAvailable = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditAvailable.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditAvailable.setObjectName("lineEditAvailable")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditAvailable)
        self.comboBoxSalesGroupName = QtWidgets.QComboBox(self.scrollAreaWidgetContents)
        self.comboBoxSalesGroupName.setEnabled(False)
        self.comboBoxSalesGroupName.setEditable(True)
        self.comboBoxSalesGroupName.setObjectName("comboBoxSalesGroupName")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBoxSalesGroupName)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(DialogEditItemSold)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.pushButtonSave = QtWidgets.QPushButton(DialogEditItemSold)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout.addWidget(self.pushButtonSave)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogEditItemSold)
        QtCore.QMetaObject.connectSlotsByName(DialogEditItemSold)
        DialogEditItemSold.setTabOrder(self.scrollArea, self.pushButtonCancel)
        DialogEditItemSold.setTabOrder(self.pushButtonCancel, self.pushButtonSave)

    def retranslateUi(self, DialogEditItemSold):
        _translate = QtCore.QCoreApplication.translate
        DialogEditItemSold.setWindowTitle(_translate("DialogEditItemSold", "Edit item sold"))
        self.label_6.setText(_translate("DialogEditItemSold", "MTS POS"))
        self.label_3.setText(_translate("DialogEditItemSold", "Item name"))
        self.label_2.setText(_translate("DialogEditItemSold", "OnHand"))
        self.label_4.setText(_translate("DialogEditItemSold", "Available"))
        self.label.setText(_translate("DialogEditItemSold", "Sale group"))
        self.pushButtonCancel.setText(_translate("DialogEditItemSold", "Cancel"))
        self.pushButtonSave.setText(_translate("DialogEditItemSold", "Save"))
