# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\raccoondale\Documents\Personal\Git\mts-pos\app\views\templates\EditSupplier.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DialogEditSupplier(object):
    def setupUi(self, DialogEditSupplier):
        DialogEditSupplier.setObjectName("DialogEditSupplier")
        DialogEditSupplier.resize(699, 506)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogEditSupplier)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(DialogEditSupplier)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 699, 465))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditSupplierName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditSupplierName.setObjectName("lineEditSupplierName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditSupplierName)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.widget = QtWidgets.QWidget(DialogEditSupplier)
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(self.widget)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.pushButtonSave = QtWidgets.QPushButton(self.widget)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_2.addWidget(self.pushButtonSave)
        self.verticalLayout.addWidget(self.widget)

        self.retranslateUi(DialogEditSupplier)
        QtCore.QMetaObject.connectSlotsByName(DialogEditSupplier)

    def retranslateUi(self, DialogEditSupplier):
        _translate = QtCore.QCoreApplication.translate
        DialogEditSupplier.setWindowTitle(_translate("DialogEditSupplier", "Edit supplier"))
        self.label_3.setText(_translate("DialogEditSupplier", "Supplier name"))
        self.pushButtonCancel.setText(_translate("DialogEditSupplier", "Cancel"))
        self.pushButtonSave.setText(_translate("DialogEditSupplier", "Save"))
