# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/mimoy/Documents/GitHub/mts-pos/app/views/templates/generated\EditReward.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
sys.path.append(os.path.abspath(''))  # required to change the default path
from app.utils.pyqt5 import QtWidgets, QtCore, QtGui


class Ui_DialogEditReward(object):
    def setupUi(self, DialogEditReward):
        DialogEditReward.setObjectName("DialogEditReward")
        DialogEditReward.resize(878, 634)
        self.verticalLayout = QtWidgets.QVBoxLayout(DialogEditReward)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.scrollArea = QtWidgets.QScrollArea(DialogEditReward)
        self.scrollArea.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 878, 593))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayout = QtWidgets.QFormLayout(self.scrollAreaWidgetContents)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.lineEditRewardName = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditRewardName.setObjectName("lineEditRewardName")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEditRewardName)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.lineEditPoints = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditPoints.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditPoints.setObjectName("lineEditPoints")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEditPoints)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEditTarget = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditTarget.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEditTarget.setObjectName("lineEditTarget")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEditTarget)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEditDescription = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.lineEditDescription.setObjectName("lineEditDescription")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.lineEditDescription)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout.addWidget(self.scrollArea)
        self.widgetConfirmationButton = QtWidgets.QWidget(DialogEditReward)
        self.widgetConfirmationButton.setObjectName("widgetConfirmationButton")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widgetConfirmationButton)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(self.widgetConfirmationButton)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout_2.addWidget(self.pushButtonCancel)
        self.pushButtonSave = QtWidgets.QPushButton(self.widgetConfirmationButton)
        self.pushButtonSave.setObjectName("pushButtonSave")
        self.horizontalLayout_2.addWidget(self.pushButtonSave)
        self.verticalLayout.addWidget(self.widgetConfirmationButton)

        self.retranslateUi(DialogEditReward)
        QtCore.QMetaObject.connectSlotsByName(DialogEditReward)

    def retranslateUi(self, DialogEditReward):
        _translate = QtCore.QCoreApplication.translate
        DialogEditReward.setWindowTitle(_translate("DialogEditReward", "Edit reward"))
        self.label_3.setText(_translate("DialogEditReward", "Reward name"))
        self.label_2.setText(_translate("DialogEditReward", "Points"))
        self.label_4.setText(_translate("DialogEditReward", "Target"))
        self.label.setText(_translate("DialogEditReward", "Description"))
        self.pushButtonCancel.setText(_translate("DialogEditReward", "Cancel"))
        self.pushButtonSave.setText(_translate("DialogEditReward", "Save"))
