# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mimoy\Documents\GitHub\mts-pos\app\views\templates\Loading.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormLoading(object):
    def setupUi(self, FormLoading):
        FormLoading.setObjectName("FormLoading")
        FormLoading.setWindowModality(QtCore.Qt.ApplicationModal)
        FormLoading.resize(221, 60)
        self.verticalLayout = QtWidgets.QVBoxLayout(FormLoading)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(FormLoading)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.progressBarCount = QtWidgets.QProgressBar(self.frame)
        self.progressBarCount.setProperty("value", 24)
        self.progressBarCount.setTextVisible(False)
        self.progressBarCount.setObjectName("progressBarCount")
        self.verticalLayout_2.addWidget(self.progressBarCount)
        self.labelMessage = QtWidgets.QLabel(self.frame)
        self.labelMessage.setObjectName("labelMessage")
        self.verticalLayout_2.addWidget(self.labelMessage)
        self.verticalLayout.addWidget(self.frame)

        self.retranslateUi(FormLoading)
        QtCore.QMetaObject.connectSlotsByName(FormLoading)

    def retranslateUi(self, FormLoading):
        _translate = QtCore.QCoreApplication.translate
        FormLoading.setWindowTitle(_translate("FormLoading", "Loading"))
        self.labelMessage.setText(_translate("FormLoading", "<Message>"))
