# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/mimoy/Documents/GitHub/mts-pos/app/views/templates/generated\LoadData.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import os, sys
sys.path.append(os.path.abspath(''))  # required to change the default path
from app.utils.pyqt5 import QtWidgets, QtCore, QtGui


class Ui_DialogLoadData(object):
    def setupUi(self, DialogLoadData):
        DialogLoadData.setObjectName("DialogLoadData")
        DialogLoadData.resize(322, 93)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(DialogLoadData)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.progressBarLoad = QtWidgets.QProgressBar(DialogLoadData)
        self.progressBarLoad.setProperty("value", 0)
        self.progressBarLoad.setTextVisible(False)
        self.progressBarLoad.setTextDirection(QtWidgets.QProgressBar.TopToBottom)
        self.progressBarLoad.setObjectName("progressBarLoad")
        self.verticalLayout.addWidget(self.progressBarLoad)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelDataRepresentation = QtWidgets.QLabel(DialogLoadData)
        self.labelDataRepresentation.setObjectName("labelDataRepresentation")
        self.horizontalLayout_2.addWidget(self.labelDataRepresentation)
        self.labelLoadPercentage = QtWidgets.QLabel(DialogLoadData)
        self.labelLoadPercentage.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelLoadPercentage.setObjectName("labelLoadPercentage")
        self.horizontalLayout_2.addWidget(self.labelLoadPercentage)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButtonCancel = QtWidgets.QPushButton(DialogLoadData)
        self.pushButtonCancel.setObjectName("pushButtonCancel")
        self.horizontalLayout.addWidget(self.pushButtonCancel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(DialogLoadData)
        QtCore.QMetaObject.connectSlotsByName(DialogLoadData)

    def retranslateUi(self, DialogLoadData):
        _translate = QtCore.QCoreApplication.translate
        DialogLoadData.setWindowTitle(_translate("DialogLoadData", "Loading"))
        self.labelDataRepresentation.setText(_translate("DialogLoadData", "<DataRepresentation>"))
        self.labelLoadPercentage.setText(_translate("DialogLoadData", "<LoadPercentage>"))
        self.pushButtonCancel.setText(_translate("DialogLoadData", "Cancel"))
