# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\mimoy\Documents\GitHub\mts-pos\app\views\templates\ManageActionButton.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormManageActionButton(object):
    def setupUi(self, FormManageActionButton):
        FormManageActionButton.setObjectName("FormManageActionButton")
        FormManageActionButton.resize(498, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(FormManageActionButton)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButtonEdit = QtWidgets.QPushButton(FormManageActionButton)
        self.pushButtonEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonEdit.setObjectName("pushButtonEdit")
        self.horizontalLayout.addWidget(self.pushButtonEdit)
        self.pushButtonView = QtWidgets.QPushButton(FormManageActionButton)
        self.pushButtonView.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonView.setObjectName("pushButtonView")
        self.horizontalLayout.addWidget(self.pushButtonView)
        self.pushButtonDelete = QtWidgets.QPushButton(FormManageActionButton)
        self.pushButtonDelete.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonDelete.setObjectName("pushButtonDelete")
        self.horizontalLayout.addWidget(self.pushButtonDelete)
        self.pushButtonAdd = QtWidgets.QPushButton(FormManageActionButton)
        self.pushButtonAdd.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonAdd.setObjectName("pushButtonAdd")
        self.horizontalLayout.addWidget(self.pushButtonAdd)
        self.pushButtonDiscount = QtWidgets.QPushButton(FormManageActionButton)
        self.pushButtonDiscount.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonDiscount.setObjectName("pushButtonDiscount")
        self.horizontalLayout.addWidget(self.pushButtonDiscount)
        self.pushButtonVoid = QtWidgets.QPushButton(FormManageActionButton)
        self.pushButtonVoid.setMinimumSize(QtCore.QSize(0, 0))
        self.pushButtonVoid.setObjectName("pushButtonVoid")
        self.horizontalLayout.addWidget(self.pushButtonVoid)

        self.retranslateUi(FormManageActionButton)
        QtCore.QMetaObject.connectSlotsByName(FormManageActionButton)

    def retranslateUi(self, FormManageActionButton):
        _translate = QtCore.QCoreApplication.translate
        FormManageActionButton.setWindowTitle(_translate("FormManageActionButton", "Form"))
        self.pushButtonEdit.setText(_translate("FormManageActionButton", "Edit"))
        self.pushButtonView.setText(_translate("FormManageActionButton", "View"))
        self.pushButtonDelete.setText(_translate("FormManageActionButton", "Delete"))
        self.pushButtonAdd.setText(_translate("FormManageActionButton", "Add"))
        self.pushButtonDiscount.setText(_translate("FormManageActionButton", "Discount"))
        self.pushButtonVoid.setText(_translate("FormManageActionButton", "Void"))
