EVENT_NO_EVENT = 'no-event'
EVENT_START_LOGIN = 'start/login'
EVENT_START_SETUP = 'start/setup'
EVENT_START_SIGNUP = 'start/signup'
EVENT_START_MANAGE = 'start/manage'
EVENT_START_TESTER = 'start/tester'