-- Drop the tables in reverse order of their dependencies

DROP TABLE IF EXISTS "Sale";
DROP TABLE IF EXISTS "UserSession";
DROP TABLE IF EXISTS "ItemPrice";
DROP TABLE IF EXISTS "Stock";
DROP TABLE IF EXISTS "Item";
DROP TABLE IF EXISTS "User";
DROP TABLE IF EXISTS "Member";
DROP TABLE IF EXISTS "Supplier";
DROP TABLE IF EXISTS "Promo";
DROP TABLE IF EXISTS "Reward";
DROP TABLE IF EXISTS "SalesGroup";
DROP TABLE IF EXISTS "ItemType";
DROP TABLE IF EXISTS "Brand";
DROP TABLE IF EXISTS "Organization";
DROP TABLE IF EXISTS "Date";
DROP TABLE IF EXISTS "OrderType",
DROP TABLE IF EXISTS "Receipt",
DROP TABLE IF EXISTS "Reason",
DROP TABLE IF EXISTS "ItemSold",
DROP TABLE IF EXISTS "POSConfig",
